### ISSUE TITLE
Rajouter un champ "email" au formulaire qui permet de s'enregistrer

### ISSUE THREAD

**Issue by virgile-dev** [regardscitoyens/consultation_an#1]
Salut, 

De ce que je comprends, une mécanique d'inscription complète (avec validation email) n'est pas en place pour faciliter au maximum les contributions. 

Je trouve dommage de ne pas proposer aux contributeurs de laisser leur adresse email dans le formulaire `S'enregistrer` car nous ne pourrons pas dans le futur les tenir au courant de l'avancée du projet et éventuellement les associer pour des opérations similaires à venir. 

Qu'en dîtes-vous?

A+

**Comment by RouxRC** [comment]
Plutôt pour, en explicitant bien que le mail est facultatif et simplement pour être tenu informé, pour éviter de perdre des inscriptions potentielles

**Comment by teymour** [comment]
A priori, je voyais un double problème à cette demande : 
- gouvernance sur l'usage de cette information au sein du partenariat DOs, RC, PbSolving ;
- vérification de l'email (risque d'avoir des mails inscrits automatiquement sans accord de leur propriétaire).

Après discussion avec @RouxRC, si on est d'accord entre orgas qu'on utilise ces mails que pour la suite donnée à cette initiative, ça me semble OK.

Pour le second, on peut peut être dire qu'on n'utilisera que les mails des gens qui ont contribué au moins une fois (ca limite les risques d'utilisation par des robots.

Si ça vous va, j'ai fait évoluer le formulaire avec une 2de section : 

---

```
Pour être tenu informé de la suite donnée à cette initiative, n'hésitez pas à nous laissez votre email :

      Email :  [ citoyens@exemple.fr ]

Votre email ne sera utilisé que pour vous tenir informé de la suite donnée au projet « Aidons l'Assemblée à écouter les citoyens ». Les trois organisations participantes ne les utiliseront pas à d'autres fins.
```

---

**Comment by teymour** [comment]
Proposition poussée 889dca0

**Comment by virgile-dev** [comment]
Ok, ça marche pour moi aussi!
Merci de votre réponse.
