### ISSUE TITLE
Le camembert indiquant la complétion de la tâche semble être beuggué.

### ISSUE THREAD

**Issue by virgile-dev** [regardscitoyens/consultation_an#3]
Salut! 

Le camembert de la section statistique qui indique la complétion de la tâche a l'air de ne pas fonctionner. Au moment où j'écris ce message Il y a eu 771 contributions par 149 citoyens et pourtant le camembert indique toujours que 99% de la tâche reste à réaliser. Je trouve que c'est un peu décourageant pour les citoyens qui participent.

<img width="475" alt="capture d ecran 2016-10-12 a 18 12 45" src="https://cloud.githubusercontent.com/assets/11473995/19318145/b4daf3f2-90a7-11e6-8ca7-d1e150eb3ab0.png">

Cela dit j'ai peut être mal compris le fonctionnement du dit camembert. 

Merci d'avance.

**Comment by fmassot** [comment]
yep, on en a discuté avec @kerneis et @RouxRC et il faudrait tester une autre façon de présenter les résultats : par exemple ajouter une catégorie "en cours" en plus de la catégorie "done" ou "todo"

**Comment by virgile-dev** [comment]
Je comprends pas trop comment il fonctionne du coup ce module statistique. 
De ce que j'avais compris : 598 x 3 = 1794 donc pour moi 771 évaluations = 43% non?

**Comment by fmassot** [comment]
pour valider des contributions, il faut avoir exactement les mêmes au moins 3 fois. Et il me semble qu'il y a 5 questions qualitatives.

Après on est jamais à l'abri d'un bug :)

**Comment by boogheta** [comment]
la validation a lieu quand 3 ont soumis la même chose, il faut investiguer un peu dans les données pour vérifier mais il est possible qu'il y ait eu beaucoup d'évaluations différentes ne permettant pas de valider de contribution... à creuser...

Sinon pour l'idée du " en cours", le danger est que très vite avec le random en fait tout soit en cours et rien en todo, du coup ca ne reglerait pas le souci.
j'aurai plutot tendance à essayer de tricher et afficher dans un premier temps dans le camembert une proportion fictive de nb d'évaluations / (5 x nb de contributions à évaluer)
Comme ca on est large a priori et ça avance, et quand on aura passé les 50% on pourra rebasculer sur le mode normal avec potentiellement meêm un petit saut à ce moment.

**Comment by fmassot** [comment]
+1 pour ta solution @RouxRC vu qu'on va vite arriver à 90% de "en cours"

**Comment by virgile-dev** [comment]
OK pour moi aussi! Merci @RouxRC !

**Comment by RouxRC** [comment]
En fait c'était bien buggé :)
On affichait le ratio au lieu du pourcentage du coup ça ne pouvait pas dépasser 1 :/
Plus besoin de tricher du coup!

et faudra que @teymour nous explique en rentrant son truc de tenir compte des jours restants aussi ;)

**Comment by fmassot** [comment]
ah c quand même bon d'avoir les deux profils de @RouxRC et @boogheta sur un même thread !

**Comment by teymour** [comment]
Les jours visent a prendre en compte le fait que tous les matins, il y a de nouvelles donnees jusqua la fin de la consultation. Si tu es qu`a la moitie de la consultation tu ne peux pas dire que l´analyse est > a 0.5, sinon c´est super deceptif quand de nouvelles donnees sont integrees car le ratio diminue (je suis d´accord que le 99% n´etait pas mieux :) )

Faire un ratio simplement de done / total ne me parait pas un tres bon choix. C´est pour ca que j´avais mis :
    done / total \* nb-jours-depuis-debut-consultation / nb-jours-total-de-consultation

(desole ce message est ecrit d´un clavier portugais...)

**Comment by RouxRC** [comment]
sauf que ça ne rêgle pas le problème : ça réduit le maximum atteignable mais ça ne permet pas d'assurer que le pourcentage ne diminue pas, il faudrait compter séparément dans le total les documents en fonction de leur jour d'arrivée mais ça me parait bien compliqué.
On se disait avec @fmassot qu'on pourrait plutôt ajouter dans la description du dessous `(dont N nouveaux ce matin)` quand on a des documents insérés le jour-même, comme ça le chiffre est réel et la baisse compréhensible
